name: CI

on:
  push:
    branches: [ main, work ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          cd app
          npm install
      - name: Lint
        run: |
          cd app
          npm run lint
      - name: Build
        run: |
          cd app
          npm run build
